### PR TITLE
Add diagnostic 3 to the notebooks 5-8

### PR DESCRIPTION
**Pull request by rbeucher**
HI @flicj191,

Please have a look at those diagnostics 3. Let me know what you think.

### CODE REVIEW

**Review by flicj191 — COMMENTED** [review]
The axis_statistics isn't working for me in 05-double_ITCZ_sea_cycle, it does a mean along the month number.  and in the description it should be showing along the latitude, not longitude along the bottom.
Others looking ok but 08 is missing the preprocessors for diagnostic 3.
did you want me to edit @rbeucher ?

**Comment by rbeucher** [comment]
Thanks @flicj191 Feel free to edit yes

**Review by flicj191 — APPROVED** [review]
did you want to have a look? @rbeucher

**Comment by rbeucher** [comment]
I'll merge and go through it again.

**Pull request merged**
